name: dexp-env
channels:
  - conda-forge
  - openeye
  - defaults
dependencies:
  - python==3.9
  - openff-toolkit-base==0.10.7
  - openff-evaluator==0.3.11
  - openff-units==0.1.6
  - openff-utilities==0.1.5
  - pint==0.19.2
  - smirnoff-plugins==0.0.3
  - openff-bespokefit
  - openff-qcsubmit
  - pydantic
  - openeye-toolkits==2021.2.0
  - forcebalance==1.9.3
  - openmm==7.7.0
  - pymbar==3.0.7
  - torsiondrive
  - geometric
  - cmiles
  - ndcctools
  - ambertools
  - openff-forcefields
  - openmmforcefields==0.11.0
  - conda-forge::libiconv
  - click
  - seaborn
  - jupyter
  - pandas=1.5.3 # https://github.com/openforcefield/openff-evaluator/issues/506
  - dask==2023.5.0
  - distributed==2023.5.0
  - dask-jobqueue >=0.8.0
