name: double-exp-vdw

channels:
  - conda-forge
  - simonboothroyd
  - openeye
  - defaults

dependencies:

  - python
  - pip

  - openeye-toolkits

  # Common dependencies
  - tqdm
  - seaborn

  # vdW fitting
  - cudatoolkit=11.0
  - openmm <7.6|>7.6
  - openff-evaluator-base >=0.3.8
  - nonbonded >= 0.0.1b4
  - dask ==2.30.0
  - distributed ==2.30.1
  - mdtraj ==1.9.4
  - smirnoff-plugins >=0.0.2

  # Transfer free energy benchmarks
  - absolv
