name: double-exp-vdw

channels:
  - simonboothroyd
  - openeye
  - conda-forge
  - defaults

dependencies:

  - python
  - pip

  - openeye-toolkits

  # Common dependencies
  - tqdm
  - seaborn

  # vdW fitting
  - openff-evaluator >=0.3.6
  - nonbonded >= 0.0.1b1
  - distributed ==2.30.1
  - mdtraj ==1.9.4
  - smirnoff-plugins >=0.0.2
